//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.17 at 08:09:40 PM CEST 
//


package com.blazebit.data.cfg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.blazebit.data.cfg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.blazebit.data.cfg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataConfig }
     * 
     */
    public DataConfig createDataConfig() {
        return new DataConfig();
    }

    /**
     * Create an instance of {@link DataClass }
     * 
     */
    public DataClass createDataClass() {
        return new DataClass();
    }

    /**
     * Create an instance of {@link DataLookup }
     * 
     */
    public DataLookup createDataLookup() {
        return new DataLookup();
    }

    /**
     * Create an instance of {@link DataLookupBy }
     * 
     */
    public DataLookupBy createDataLookupBy() {
        return new DataLookupBy();
    }

    /**
     * Create an instance of {@link DataProperty }
     * 
     */
    public DataProperty createDataProperty() {
        return new DataProperty();
    }

}
